sudo: required
services:
- docker
before_script:
- docker pull navikt/glide
- docker pull golang:1.8
- docker pull navikt/helm
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- git clone https://github.com/nais/charts
script:
- make install test linux
- "/bin/bash bump.sh $GH_TOKEN"
- git tag -a $(/bin/cat ./vrs) -m "auto-tag from Makefile [skip ci]" && git push --tags
  https://$GH_TOKEN@github.com/nais/gardener
- make docker-build push-dockerhub
- cd charts
- docker run -v $(pwd):/charts -v $(pwd)/../:/gardener -w /charts navikt/helm package
  /gardener/helm/gardener
- docker run -v $(pwd):/charts -w /charts navikt/helm repo index --url https://nais.github.io/charts
  .
- echo "<html><body><pre>$(cat index.yaml)</pre></body></html>" > index.html
- git add --all
- git commit -m "auto-update by travis [skip ci]"
- git push https://$GH_TOKEN@github.com/nais/charts
- cd ..
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: nais-*
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
  - master
env:
  global:
  - secure: LU1CPHoaabPH1Bm8o9lfSeeZAWAuuttGpDq0U+C2baBStsy8+gwzi/KkJjR4iCKAbgQ/kf9PbYlfDyB/3OjS73xMp4APAbOXH82s11V7mZuhL0cR1tlEJ3vSwIffMLACO7fCjaCKAtB9HF4wwt1e4jlMrKzHvtrQMCNloN5LyEqQTLinFjgP4VaM5nqBtWYc9DymyJnOPeN43mTz1da/fLtn5Mar5nc4gMKltISKisNK1jQfVCqHz55sSDIiHvIn0DyqMsE5Wzok+fcuTbAeBsuxf5pIIdKcOyTNn/9Ub47tZLcBD0vpIY/FIrSQiFPk2+JKeGkB90CUjiDsKsViki6m4uFop+nxrGcw6fHLHav5/jBwotyUSseHSHqm22WXv2G5z3lDZnSXwDyZipA7x9wT4tGmUeOphDzvo93vkc7zdTNBKKXAHitQWAynPJGNnu8An1fw/cOhYvR497vZCRPN1doGJNKf5Sx5XNEJ3vr3vHgfbRyClf1DthO4WWzcY3m6yzhL07ywBvT5pXxbBVALSfpbaz+GpMJH7G8OPDlgbx5Z4MxL3X/EZ3a3YrV66E7VnY8XtU7eMlY1gMLdHgBW0WarNbFnm6hhw6rHqHXyye+VciHbTiNvkuSzRhMsF5D2HDgLO0ryqN07oLaPHpvYXB/tksZmyJm+VkXA1FQ=
  - secure: SoOERyHwUDVNB8eJvaBYUjm9jY2qP85rSAbaE7wCOS3dmml+JdR6B+eCkGFQS7EEMWyC34v2tS4jrTFRQxfAVk/BZpB2Wji8D2Q7YUejqGBhdJBhQUySYkUxAEz4AA/tgeO8YkCR8Z6j4uNNWRurU+zCfpuPOvWvbkmwFT4KFZwPISjQ7MDHWFI8Of9HLtUyoCII4XkYb7vaPgF6PM3RXsBobjo2pQUA4YVCwsQ0jGRLgfcm3Yl6JhMWv5xoF4CviszLwT7BKGG/pNdXwxknq/tILjbRPfT8hqvo+u8PWFwocbIk/9UuMlDZb24thQpk/ADxb81FYU5qGzhs6bZoZA8Jb9R1RNejpapY16YE2uxLVA8DQJ6flRbSHguRXsrfMWlSwyuwIHgcrleSLkYLgTJ4Npa/uGiWhxdR/mEAnHXx1W94eTarQYgW6d03Z+iB77UQn29aGAqPRs9QubmWxCYwEHKb2wUlU5ABp+AhIuPOUe6VvLQOSs2agQ2bycjeTPrh39WBuUpsqnNJEAyd3CiZmA91NnNuADJaLnPtR5zdTA3ejcr4i52C6at6aLxaJc5DCyZSmi9dBEGyy1+n5zoGY/f3CU47zge3nRqk/Fyr46hh3edTfGCQoc9PcnaLuVRMDe8b/VvEIqgDEAjoUOnZ3EQnZIEfpzfnhZBAcCM=
  - secure: m+Z/o/h0AYExqVm6VhMxWhCcF5T50cANaFGHfpkjIdBF9aGxC0A6K1AWYmdyM5VXtUd3jJ3WM5MFCCWqWFVTnA8MgSFT0Zlais0vLR81+X1jEc1CUl1ZHRqb9f+X2KBXqxL2eyn6EmPz4RGl1QE65Kncl0PO6GA0CHzNofT0g1mDoJvMgQVlaPfYt3FvQh3YP+scOVT8uD1ur85QNevzCrMWMMA8ufxhxYlEN66Fad6uyU2vkoSVmSyoJlCt/TGOex+A7GpHFaPIzkIaCg+lkLaFmudyEjmhTqV/xKHt/fS0MlO2wevlKaW4d8G8R04xMgMqJYQM4qc2ljbqfXR0ov5T76A78DU+SifoPdwtg5Djpqv/saUQZVt5cJZ32EEACzodaaRG2UFlJco8HiLfb2+V/S/iivohcY885vP/gxHNFfc2tRY5qin0tydv+06rqKVKYCL2ON5IAIddIM9+H0hB2rOggNsi8g80vEf56dkX6EjboOGxBT0G/cO/MMGJbVlktptOt4PshQkyPiYaOjPUMzv9AcY41etRbrCzF+dSdzdNDP9t/7HskXEVgfHcL8+HbjLv1eJ3aB1ywJcZh6T0iyHZJavTlmZ6YTiFbV0qTWRsTBxduCURJDCridYSgfQNrBZ/mJc6IPpzsiYlJaYi6NfodbHFOdUezy1094k=
