apiVersion: v1
kind: Pod
metadata:
 name: stopping-container
 labels:
   purpose: restarting
spec:
 containers:
 - name: exit-1
   image: alpine
   command: ["exit"]
   args: ["1"]
 restartPolicy: OnFailure